type SevenModels = readonly [string, string, string, string, string, string, string];
type Brand = { name: string; models: SevenModels };
const catalog = (entries: Record<string, SevenModels>): readonly Brand[] =>
  Object.entries(entries).map(([name, models]) => ({ name, models }));

export const MARKET_SPORTS_BRANDS = {
  surfing: catalog({
    'Channel Islands': ['Happy Everyday', 'Two Happy', 'Neck Beard 3', 'Rocket Wide', 'Bobby Quad', 'Mid', 'Twin Pin'],
    Firewire: ['Seaside', 'Domin', 'Too Fish', 'Mashup', 'Sweet Potato', 'Revo', 'Midas'],
    Lost: ['Puddle Jumper', 'Rocket Redux', 'Driver 3.0', 'RNF 96', 'Sub Driver 2.0', 'Quiver Killer', 'California Twin'],
    JS: ['Monsta 10', 'Xero', 'Xero Gravity', 'Big Baron', 'Black Baron', 'Flame Fish', 'Raging Bull'],
    Pyzel: ['Ghost', 'Phantom', 'Shadow', 'Astro Pop', 'White Tiger', 'Gremlin', 'Mid Length Crisis'],
    'DHD': ['3DV', 'Sweet Spot 3.0', 'MF DNA', 'Twin Fin', 'Black Diamond', 'Phoenix', 'DX1'],
    'Haydenshapes': ['Hypto Krypto', 'Holy Grail', 'White Noiz', 'Loot', 'Misc.', 'Shred Sled', 'Hypto Twin'],
    'Sharp Eye': ['Inferno 72', 'Storms', 'Disco Inferno', 'HT2', 'Synergy', 'Modern 2', 'File Fifty'],
    'Torq': ['Mod Fish', 'Mod Fun', 'Mod Mini', 'TET Longboard', 'TEC Fish', 'ACT Prepreg', 'Chancho'],
    'Softech': ['Flash', 'Roller', 'Bomber', 'Mason Twin', 'Sally Fitzgibbons', 'Wildfire', 'Handshaped']
  }),
  fitness: catalog({
    'Bowflex': ['SelectTech 552', 'SelectTech 1090', 'Max Trainer M6', 'Max Trainer M9', 'Treadmill 10', 'VeloCore', 'PR3000'],
    'Technogym': ['MyRun', 'Skillrun', 'Skillmill', 'Bike', 'Bench', 'Kinesis', 'Unica'],
    'NordicTrack': ['Commercial 1750', 'X24', 'S22i', 'R35', 'RW900', 'Vault', 'Fusion CST'],
    'Life Fitness': ['IC7', 'Club Series', 'Signature Series', 'Insignia', 'Heat Row', 'Activate', 'Axiom'],
    'Rogue Fitness': ['Ohio Bar', 'Echo Bike', 'Monster Lite', 'Rogue Bumper', 'Kettlebell', 'Echo Rower', 'Flat Utility Bench'],
    'Decathlon': ['Corength', 'Domyos', 'Woodrower', 'Run500', 'EB 520', 'Bench 900', 'Dumbbell 20 kg'],
    'Peloton': ['Bike', 'Bike+', 'Tread', 'Tread+', 'Row', 'Guide', 'Weights'],
    'Concept2': ['RowErg', 'SkiErg', 'BikeErg', 'Dynamic Indoor Rower', 'Model D', 'Model E', 'PM5'],
    'Hammer Strength': ['Iso-Lateral', 'Plate Loaded', 'MTS', 'Select', 'HD Elite', 'Ground Base', 'Linear Leg Press'],
    'TRX': ['PRO4', 'HOME2', 'MOVE', 'Duo Trainer', 'Rip Trainer', 'YBell', 'Bandit']
  }),
  yoga: catalog({
    Manduka: ['PRO', 'PROlite', 'eKO', 'eKO lite', 'GRP Adapt', 'Begin', 'X Mat'],
    Liforme: ['Original', 'Travel', 'XL', 'Classic', 'Rainbow', 'Cosmic Moon', 'White Magic'],
    JadeYoga: ['Harmony', 'Voyager', 'Fusion', 'Travel', 'Elite S', 'Level One', 'Calm'],
    AloYoga: ['Warrior Mat', 'Air Mat', 'Grounded No-Slip', 'Uplifting Block', 'Yoga Strap', 'Carry Sling', 'Pose Towel'],
    Gaiam: ['Premium Print', 'Dry-Grip', 'Performance', 'Reversible', 'Cork', 'Yoga Essentials', 'Foldable'],
    Lululemon: ['The Mat 5mm', 'The Reversible Mat', 'The Lightweight Mat', 'The Workout Mat', 'Lift and Lengthen', 'Double Roller', 'Take Form'],
    'B Yoga': ['B MAT Everyday', 'B MAT Strong', 'B MAT Traveller', 'B MAT Impact', 'B BLOCK', 'B STRAP', 'B CORK'],
    YogiBare: ['PAWS', 'PAWS Travel', 'EverGrip', 'Acupressure Mat', 'Yoga Block', 'Yoga Strap', 'Hot Yoga Towel'],
    'Hugger Mugger': ['Tapas Original', 'Para Rubber', 'Nature Collection', 'Standard Bolster', 'Pranayama Bolster', 'Cork Block', 'Cotton Strap'],
    'Yoga Design Lab': ['Combo Mat', 'Infinity Mat', 'Travel Mat', 'Cork Mat', 'Yoga Wheel', 'Hand Towel', 'Yoga Strap']
  }),
  padel: catalog({
    Bullpadel: ['Vertex 04', 'Hack 04', 'Ionic Power', 'Neuron', 'Flow', 'Elite', 'Pearl'],
    Nox: ['AT10 Genius', 'ML10 Pro Cup', 'LA10 Quantum', 'Future Control', 'Equation', 'Tempo', 'MP10 Luxury'],
    Adidas: ['Metalbone', 'Adipower', 'Cross It', 'RX Series', 'Drive', 'Essnova', 'Match'],
    Head: ['Extreme Pro', 'Speed Pro', 'Gravity Pro', 'Vibe', 'Evo Speed', 'Cyber', 'Zephyr'],
    Babolat: ['Technical Viper', 'Air Viper', 'Counter Viper', 'Technical Veron', 'Air Veron', 'Counter Veron', 'Contact'],
    Wilson: ['Bela Pro', 'Bela Elite', 'Blade Pro', 'Blade Team', 'Carbon Force', 'Pro Staff', 'Ultra Team'],
    Siux: ['Electra ST3', 'Diablo Pro', 'Fenix Pro', 'Pegasus', 'Astra', 'Trilogy', 'Beat Hybrid'],
    StarVie: ['Metheora', 'Triton', 'Dronos', 'Raptor', 'Kenta', 'Astrum', 'Basalto'],
    Varlion: ['Bourne', 'Maxima', 'LW', 'Avant', 'Summum', 'Prisma', 'Carbon Black'],
    'Black Crown': ['Pitón', 'Hurricane', 'Special', 'Piton Attack', 'Cobra', 'Reverso', 'Win']
  }),
  tennis: catalog({
    Wilson: ['Pro Staff 97', 'Blade 98', 'Clash 100', 'Ultra 100', 'Shift 99', 'Burn 100', 'Triad Three'],
    Babolat: ['Pure Aero', 'Pure Drive', 'Pure Strike', 'Evo Drive', 'Boost Drive', 'Ballfighter', 'Junior 25'],
    Head: ['Speed MP', 'Radical MP', 'Gravity MP', 'Extreme MP', 'Boom MP', 'Prestige Pro', 'Instinct MP'],
    Yonex: ['EZONE 98', 'EZONE 100', 'VCORE 98', 'VCORE 100', 'PERCEPT 97', 'PERCEPT 100', 'ASTREL 100'],
    Dunlop: ['CX 200', 'CX 400', 'SX 300', 'FX 500', 'Nitro 27', 'Tristorm Pro', 'Fort All Court'],
    Prince: ['Tour 100', 'Phantom 100', 'Beast 100', 'Warrior 100', 'Textreme Tour', 'Ripstick', 'Thunder'],
    Tecnifibre: ['T-Fight 305', 'T-Fight 300', 'TF40', 'TF-X1', 'Tempo 298', 'Carboflex', 'X-One Biphase'],
    Volkl: ['V-Cell 1', 'V-Cell 8', 'V-Cell 10', 'Vostra V1', 'Vostra V8', 'Vostra V10', 'C10 Pro'],
    Solinco: ['Whiteout 305', 'Whiteout 290', 'Blackout 300', 'Blackout 285', 'Hyper-G', 'Tour Bite', 'Confidential'],
    Artengo: ['TR960 Control Tour', 'TR930 Spin Pro', 'TR990 Power', 'TR500', 'TR190', 'TR160', 'TR100']
  }),
  swimming: catalog({
    Speedo: ['Fastskin LZR Pure Intent', 'Fastskin LZR Pure Valor', 'Biofuse 2.0', 'Vanquisher 2.0', 'Hydropulse', 'Futura Biofuse', 'Power Paddle'],
    Arena: ['Cobra Ultra Swipe', 'Cobra Core Swipe', 'The One', 'Air-Speed', 'Powerskin Carbon Air2', 'Powerskin Primo', 'Zoom X-Fit'],
    TYR: ['Blackhawk Racing', 'Special Ops 3.0', 'Tracer-X', 'Venzo', 'Avictor', 'Catalyst Stroke', 'Hurricane Cat 5'],
    FINIS: ['Smart Goggle', 'Tempo Trainer Pro', 'Zoomers Gold', 'Agility Paddle', 'Swimmer Snorkel', 'Duo', 'Hydro Hip'],
    Zoggs: ['Predator Flex', 'Predator', 'Fusion Air', 'Phantom 2.0', 'Sea Demon', 'Raptor', 'HydroX'],
    AquaSphere: ['Kayenne', 'Kaiman', 'Vista', 'Seal 2.0', 'Eagle', 'Xceed', 'Pursuit'],
    NikeSwim: ['Legacy', 'Remora', 'Chrome', 'Hydrastrong', 'Poly Solid', 'Essential', 'Kick Short'],
    MadWave: ['Raptor', 'Turbo Racer', 'Alligator', 'Alien', 'Razor', 'Optic Envy', 'Training Fins'],
    Funkita: ['Diamond Back', 'Single Strap', 'Tie Me Tight', 'Twisted', 'Eco C-Infinity', 'Hipster', 'Sports Brief'],
    Mizuno: ['GX-Sonic', 'Stream Ace', 'Exer Suit', 'Wave Exceed', 'Stream Aqucela', 'N2JY', 'Bio Gear']
  }),
  martial_arts: catalog({
    Venum: ['Elite', 'Challenger', 'Impact', 'Contender', 'Predator', 'Giant', 'Light'],
    Fairtex: ['BGV1', 'BGV14', 'BGV16', 'SP5', 'HB6', 'HB10', 'TV2'],
    'Twins Special': ['BGVL-3', 'BGVL-6', 'FBGVL-3', 'SGL-10', 'SGM-10', 'KPL-10', 'HGL-3'],
    Hayabusa: ['T3', 'T3 LX', 'S4', 'S4 Youth', 'Marvel', 'Pro Boxing', 'Geo'],
    Everlast: ['Powerlock', 'Elite', 'Pro Style', 'Spark', 'PIVT', 'Titan', '1910'],
    'Cleto Reyes': ['Training Gloves', 'Hook & Loop', 'Extra Padding', 'Safetec', 'Professional', 'Headgear', 'Speed Bag'],
    'Top King': ['Super Air', 'Ultimate', 'Pro', 'Star', 'King', 'Shin Guards', 'Head Guard'],
    AdidasCombat: ['Speed 50', 'Speed 100', 'Hybrid 100', 'Hybrid 200', 'Power 100', 'Response', 'Adistart'],
    RDX: ['F7 Ego', 'F6 Kara', 'F4', 'T1', 'Kara', 'Mark Pro', 'Maya Hide'],
    Leone1947: ['Shock', 'Flash', 'Ambassador', 'Il Tecnico', 'DNA', 'Black Edition', 'Revo']
  }),
  diving: catalog({
    Cressi: ['Start Pro', 'Travelight', 'Leonardo', 'Giotto', 'Donatello', 'MC9 Compact', 'Big Eyes Evolution'],
    Mares: ['Puck Pro+', 'Quad', 'Genius', 'Rover', 'Magellan HD', 'Avanti Quattro+', 'X-Vision'],
    Scubapro: ['MK25 EVO', 'S620 Ti', 'Hydros Pro', 'GO', 'Galileo 3', 'Jet Fin', 'Seawing Nova'],
    Aqualung: ['Legend 3', 'Core', 'Pro HD', 'Rogue', 'i300C', 'Reveal X1', 'Storm'],
    Oceanic: ['Geo 4.0', 'Veo 4.0', 'Pro Plus X', 'Delta 5', 'Biolite', 'Shadow', 'Viper'],
    Apeks: ['XTX200', 'XTX50', 'MTX-RC', 'XL4 Ocea', 'WTX-D', 'RK3', 'Luna'],
    TUSA: ['Freedom HD', 'Freedom One', 'Paragon S', 'Imprex Duo', 'Solla', 'HyFlex Switch', 'T-Wing'],
    Hollis: ['M1', 'F1', 'HD-200', 'ST Elite', '500SE', 'DC7', 'Katana 2'],
    Suunto: ['D5', 'Ocean', 'EON Core', 'EON Steel Black', 'Zoop Novo', 'Vyper Novo', 'Tank POD'],
    Garmin: ['Descent Mk3', 'Descent Mk3i', 'Descent G1', 'Descent X50i', 'Descent T2', 'Dive Case', 'Dive Band']
  }),
  snorkeling: catalog({
    Cressi: ['F1', 'Big Eyes Evolution', 'Calibro', 'Palau', 'Rondinella', 'Supernova Dry', 'Gara Modular'],
    Mares: ['X-Vision', 'Tropical', 'Pure Vision', 'Avanti Superchannel', 'Manta', 'Ergo Dry', 'Wahoo'],
    Scubapro: ['Solo', 'Zoom EVO', 'Spectra', 'GO Sport', 'Jet Sport', 'Spectra Dry', 'Devil'],
    Aqualung: ['Reveal X1', 'Reveal X2', 'Hawkeye', 'Storm', 'Express', 'Nabul', 'Air Dry'],
    TUSA: ['Freedom HD', 'Paragon S', 'Splendive', 'Sport Powerview', 'Impresa', 'Reef Tourer', 'Platinas'],
    Beuchat: ['Maxlux S', 'X-Contact 2', 'Oceo', 'Mundial One', 'Mundial Competition', 'Spy', 'Activa'],
    SEAC: ['Libera', 'Magica', 'Unica', 'Tris Spinta', 'Speed', 'Motus', 'Fast Tech Dry'],
    Aropec: ['Crystal', 'Panorama', 'Dry Top', 'Full Face', 'Freedive', 'Low Volume', 'Comfort Fin'],
    'Ocean Reef': ['Aria QR+', 'Aria Classic', 'Aria Junior', 'Neptune III', 'Aria Uno', 'Aria XS', 'Duo II'],
    FINIS: ['Swimmer Snorkel', 'Freestyle Snorkel', 'Stability Snorkel', 'Zoomers Gold', 'Smart Goggle', 'Agility Paddle', 'Rapid Monofin']
  }),
  cycling: catalog({
    Shimano: ['105 R7100', 'Ultegra R8100', 'Dura-Ace R9200', 'Deore M6100', 'SLX M7100', 'XT M8100', 'XTR M9100'],
    SRAM: ['Red AXS', 'Force AXS', 'Rival AXS', 'Apex AXS', 'GX Eagle', 'X01 Eagle', 'XX1 Eagle'],
    Campagnolo: ['Super Record', 'Record', 'Chorus', 'Ekar', 'Shamal', 'Bora', 'Zonda'],
    Trek: ['Marlin 7', 'Domane SL 5', 'Emonda SL 6', 'Madone SL 7', 'Fuel EX 8', 'FX 3', 'Rail 7'],
    Specialized: ['Tarmac SL8', 'Roubaix SL8', 'Allez', 'Diverge', 'Stumpjumper', 'Rockhopper', 'Turbo Levo'],
    Giant: ['TCR Advanced', 'Defy Advanced', 'Propel Advanced', 'Revolt', 'Talon', 'Trance', 'Escape'],
    Cannondale: ['SuperSix EVO', 'CAAD13', 'Synapse', 'Topstone', 'Scalpel', 'Trail', 'Quick'],
    Wahoo: ['ELEMNT ROAM', 'ELEMNT BOLT', 'ELEMNT ACE', 'KICKR', 'KICKR CORE', 'KICKR BIKE', 'TRACKR'],
    Garmin: ['Edge 540', 'Edge 840', 'Edge 1040', 'Edge 1050', 'Varia RTL515', 'Rally RS200', 'Tacx NEO 2T'],
    'Fox Racing': ['Speedframe', 'Proframe', 'Rampage', 'Flexair', 'Ranger', 'Defend', 'Dirtpaw']
  }),
  football: catalog({
    Adidas: ['Predator', 'F50', 'Copa Pure', 'Tiro', 'Al Rihla', 'Oceaunz', 'UCL Pro'],
    Nike: ['Mercurial Vapor', 'Mercurial Superfly', 'Phantom GX', 'Phantom Luna', 'Tiempo Legend', 'Academy', 'Premier 3'],
    Puma: ['Future', 'Ultra', 'King', 'Orbita', 'teamFINAL', 'teamLIGA', 'Attacanto'],
    NewBalance: ['Furon', 'Tekela', '442', 'FuelCell', 'Visaro', 'Audazo', 'Team'],
    Mizuno: ['Morelia II', 'Morelia Neo IV', 'Alpha', 'Monarcida Neo', 'Rebula', 'Wave Cup', 'Sala'],
    Umbro: ['Speciali', 'Velocita', 'Tocco', 'Pro Training', 'Neo', 'Medusae', 'Sala'],
    Diadora: ['Brasil Elite', 'B-Elite', 'Pichichi', 'M.Winner', 'Match Winner', 'Baggio', 'Capitano'],
    Select: ['Brillant Super', 'Numero 10', 'Classic', 'Tempo', 'Team', 'Street', 'Planet'],
    Molten: ['Vantaggio 5000', 'Vantaggio 4000', 'F5A5000', 'F5A4900', 'F5A3400', 'F5A2800', 'F5A1710'],
    Kipsta: ['F900', 'F500', 'F100', 'Agility 900', 'Viralto', 'CLR', 'Essential']
  }),
  badminton: catalog({
    Yonex: ['Astrox 100 ZZ', 'Astrox 88D Pro', 'Nanoflare 1000 Z', 'Arcsaber 11 Pro', 'Nanoflare 800 Pro', 'Astrox 77 Pro', 'Voltric Z-Force II'],
    Victor: ['Thruster Ryuga', 'Auraspeed 100X', 'DriveX 10', 'Brave Sword 12', 'Jetspeed S12', 'Thruster F', 'Auraspeed 90K'],
    LiNing: ['Axforce 80', 'Axforce 90', 'Aeronaut 9000C', 'Bladex 900', 'Turbo Charging 75', 'Halbertec 8000', 'Windstorm 72'],
    Apacs: ['Z-Ziggler', 'Lethal 10', 'Lethal 70', 'Feather Weight 55', 'Dual Power 55', 'Nano Fusion Speed', 'Virtuoso Performance'],
    Mizuno: ['Fortius 11 Power', 'Fortius 10 Power', 'Altius 01 Feel', 'Altius 03', 'Acrospeed 1', 'Acrospeed 6', 'Caliber VS Tour'],
    Babolat: ['X-Feel Origin', 'Satellight Gravity', 'Satellight Blast', 'I-Pulse Essential', 'Prime Essential', 'Jetstream 74', 'Satelite Power'],
    Forza: ['Power 988', 'Light 9', 'Precision 9000', 'Speed Light', 'Titanium 11000', 'Dynamic 6', 'Aero Power'],
    Wilson: ['Recon P3500', 'Blade 500', 'Fierce CX9000', 'Strike', 'Attacker', 'Venom', 'Pro Staff'],
    ProKennex: ['Kinetic Pro', 'Power Pro', 'Nano Pro', 'X2', 'Kinetic Tour', 'Ace', 'Nano Speed'],
    Kawasaki: ['King K9', 'Honor S6', 'Passion P23', 'Nezer 19', 'High Tension', 'Super Light', 'Master 800']
  }),
  skateboarding: catalog({
    'Santa Cruz': ['Screaming Hand', 'Classic Dot', 'Roskopp Face', 'Rob Target', 'Salba Witch Doctor', 'Shark', 'Knox Firepit'],
    Element: ['Section', 'Seal', 'Nyjah', 'Blazin', 'Hatchet', 'Timber', 'Major League'],
    'Powell Peralta': ['Ripper', 'Skull & Sword', 'Caballero Dragon', 'McGill Skull', 'Steve Saiz', 'Flight Deck', 'Andy Anderson'],
    Girl: ['OG Logo', 'Bannerot', 'Malto', 'Pacheco', 'McCrank', 'Pop Secret', 'Gass'],
    Chocolate: ['Chunk', 'Tershy', 'Roberts', 'Pennebaker', 'Perez', 'Brenes', 'One Off'],
    AntiHero: ['Eagle', 'Classic Eagle', 'Team', 'Grimple', 'Cardiel', 'Kanada', 'Shaped'],
    Baker: ['Brand Logo', 'Reynolds', 'Herman', 'Kader', 'Figgy', 'T-Funk', 'Rowan'],
    Arbor: ['Pilsner', 'Axis', 'Dropcruiser', 'Oso', 'Fish', 'Sizzler', 'Bamboo'],
    'Sector 9': ['Lookout', 'Tia Pro', 'Maverick', 'Bintang', 'Fractal', 'Tropic', 'Offshore'],
    Landyachtz: ['Dinghy', 'Tugboat', 'Drop Cat', 'Switchblade', 'Battle Axe', 'Ripper', 'ATV']
  }),
  volleyball: catalog({
    Mikasa: ['V200W', 'V300W', 'V330W', 'V360W', 'BV550C', 'BV551C', 'V400W'],
    Molten: ['V5M5000', 'V5M4500', 'V5M4000', 'V5M3500', 'V5M1500', 'V4M3000', 'V5M2000'],
    Wilson: ['AVP Official', 'AVP Oasis', 'Optx', 'Pro Tour', 'Cast Away', 'Graffiti', 'Soft Play'],
    Spalding: ['King of the Beach', 'TF-VB5', 'Extreme Pro', 'Official', 'Recreational', 'Beach Volleyball', 'Indoor Volleyball'],
    ASICS: ['Sky Elite FF 3', 'Netburner Ballistic FF 3', 'Gel-Rocket 11', 'Gel-Tactic 12', 'Gel-Upcourt 6', 'Metarise 2', 'Powerbreak FF'],
    Mizuno: ['Wave Lightning Z8', 'Wave Momentum 3', 'Wave Stealth Neo', 'Wave Voltage', 'Cyclone Speed', 'Thunder Blade', 'Wave Dimension'],
    Nike: ['HyperAce 3', 'Hyperset 2', 'Zoom HyperSpeed', 'React Hyperset', 'Zoom HyperAttack', 'Air Zoom Hyperace', 'Court Lite'],
    Adidas: ['Crazyflight', 'Novaflight', 'Stabil', 'Ligra', 'Speedcourt', 'Court Team Bounce', 'Dame Certified'],
    Kipsta: ['V900', 'V500', 'V100', 'Allsix V900', 'Allsix V500', 'Allsix V100', 'Beach VB500'],
    McDavid: ['Hex Knee Pads', 'Volley Knee', 'Compression Arm', 'Teflx', 'Elite', 'Rebound', 'Ankle Brace']
  }),
  running: catalog({
    Nike: ['Pegasus 41', 'Vomero 18', 'Alphafly 3', 'Vaporfly 4', 'Structure 25', 'InfinityRN 4', 'Zoom Fly 6'],
    Adidas: ['Adizero Adios Pro 4', 'Adizero Boston 12', 'Supernova Rise', 'Ultraboost 5', 'Adizero SL2', 'Adistar 3', 'Solar Glide 6'],
    ASICS: ['GEL-NIMBUS 27', 'GEL-KAYANO 31', 'NOVABLAST 5', 'METASPEED SKY', 'MAGIC SPEED 4', 'GT-2000 13', 'SUPERBLAST 2'],
    HOKA: ['Clifton 10', 'Bondi 9', 'Mach 6', 'Speedgoat 6', 'Arahi 7', 'Rocket X 2', 'Skyward X'],
    Brooks: ['Ghost 16', 'Glycerin 22', 'Adrenaline GTS 24', 'Hyperion Max 2', 'Launch 11', 'Caldera 8', 'Catamount 3'],
    NewBalance: ['Fresh Foam X 1080v14', 'FuelCell Rebel v4', 'FuelCell SC Elite v4', 'Fresh Foam X 880v14', '860v14', 'More v5', 'Hierro v8'],
    Saucony: ['Endorphin Pro 4', 'Endorphin Speed 4', 'Ride 18', 'Triumph 22', 'Guide 18', 'Kinvara 15', 'Peregrine 14'],
    Puma: ['Deviate Nitro 3', 'ForeverRun Nitro', 'Velocity Nitro 3', 'Magnify Nitro 2', 'Fast-R Nitro Elite 2', 'Liberate Nitro 2', 'Electrify Nitro 3'],
    Mizuno: ['Wave Rider 28', 'Wave Sky 8', 'Wave Inspire 21', 'Wave Rebellion Pro 3', 'Wave Neo Vista', 'Wave Mujin 10', 'Wave Daichi 8'],
    On: ['Cloudmonster 2', 'Cloudsurfer', 'Cloudrunner 2', 'Cloudboom Strike', 'Cloudflow 4', 'Cloudultra 2', 'Cloudswift 3']
  }),
  trekking_hiking: catalog({
    Salomon: ['X Ultra 4', 'Quest 4', 'Speedcross 6', 'XA Pro 3D', 'Outpulse', 'Cross Hike 2', 'X Ultra Alpine'],
    Merrell: ['Moab 3', 'Agility Peak 5', 'Nova 3', 'Siren 4', 'Speed Eco', 'Rogue Hiker', 'Hydro Moc'],
    'The North Face': ['VECTIV Fastpack', 'VECTIV Exploris', 'Hedgehog 3', 'Terra 55', 'Borealis', 'Apex Bionic', 'Antora'],
    Osprey: ['Atmos AG 65', 'Aether 65', 'Talon 22', 'Stratos 36', 'Farpoint 40', 'Daylite Plus', 'Kestrel 48'],
    Deuter: ['Futura 32', 'Aircontact Core', 'Speed Lite 21', 'Trail 30', 'Trans Alpine 30', 'Freescape', 'Kid Comfort'],
    Columbia: ['Newton Ridge', 'Peakfreak II', 'Facets 75', 'Newton Wander', 'Redmond III', 'Crestwood', 'Fairbanks'],
    'Black Diamond': ['Distance Carbon Z', 'Trail Back', 'Pursuit', 'Spot 400', 'Storm 500-R', 'Speed 30', 'Alpine FLZ'],
    Leki: ['Makalu FX Carbon', 'Khumbu Lite', 'Legacy Lite', 'Cressida', 'Micro Vario', 'Black Series', 'Makalu Lite'],
    'Mountain Hardwear': ['Scrambler 35', 'JMT 35', 'Bishop Pass', 'Ghost Whisperer', 'StretchDown', 'Dynama', 'Kor AirShell'],
    'Naturehike': ['Cloud Up 2', 'Mongar 2', 'Star River 2', 'Rock 60+5', 'Ultralight 40', 'Yunue', 'CWM400']
  }),
  golf: catalog({
    Titleist: ['Pro V1', 'Pro V1x', 'T100', 'T150', 'T200', 'TSR2', 'Scotty Cameron Phantom'],
    Callaway: ['Paradym Ai Smoke', 'Elyte', 'Apex Pro', 'Rogue ST', 'Chrome Tour', 'Jaws Raw', 'Odyssey Ai-One'],
    TaylorMade: ['Qi10', 'Qi35', 'P790', 'P770', 'Stealth 2', 'TP5', 'Spider Tour'],
    Ping: ['G430', 'G440', 'i230', 'Blueprint S', 'Glide 4.0', 'PLD Milled', 'Hoofer'],
    Cobra: ['DARKSPEED', 'DS-ADAPT', 'AEROJET', 'KING Tour', 'KING Forged Tec', 'Snakebite', 'Vintage'],
    Mizuno: ['JPX 925', 'Mizuno Pro 241', 'Mizuno Pro 243', 'ST-Z 230', 'T24', 'M-Craft', 'BR-D4'],
    Srixon: ['ZXi', 'ZX5 Mk II', 'ZX7 Mk II', 'Z-Star', 'Q-Star Tour', 'Cleveland RTX', 'Z-Forged II'],
    Wilson: ['Dynapower', 'Staff Model', 'D9', 'Launch Pad', 'Infinite', 'Triad', 'Duo Soft'],
    PXG: ['0311', '0211', 'Black Ops', 'Battle Ready', 'Sugar Daddy', 'Gen6', 'Gen7'],
    Honma: ['BERES', 'TW757', 'TW767', 'TR20', 'XP-1', 'D1', 'T//World']
  }),
  musical_instruments: catalog({
    Yamaha: ['P-145', 'P-225', 'PSR-E383', 'FG800', 'F310', 'TRBX174', 'YAS-280'],
    Roland: ['FP-30X', 'FP-10', 'JUNO-DS', 'FANTOM-06', 'TD-17KVX2', 'GO:KEYS 5', 'A-49'],
    Fender: ['Player Stratocaster', 'American Professional II', 'Squier Classic Vibe', 'Telecaster', 'Jazz Bass', 'Precision Bass', 'Acoustasonic'],
    Gibson: ['Les Paul Standard', 'SG Standard', 'ES-335', 'J-45', 'Hummingbird', 'Explorer', 'Flying V'],
    Ibanez: ['RG550', 'AZ2204', 'GRX70QA', 'SR300E', 'Artcore AS73', 'Tim Henson TOD10', 'AEB8E'],
    Korg: ['Minilogue XD', 'MicroKORG', 'Kross 2', 'Krome EX', 'Volca Keys', 'B2', 'Pa600'],
    Casio: ['CDP-S110', 'PX-S1100', 'CT-S300', 'SA-81', 'AP-270', 'CT-X700', 'LK-S250'],
    'Pearl': ['Export EXX', 'Decade Maple', 'Roadshow', 'Masters Maple', 'Reference One', 'Eliminator', 'Sensitone'],
    'Tama': ['Imperialstar', 'Superstar Classic', 'Starclassic', 'S.L.P.', 'Iron Cobra', 'Speed Cobra', 'Club-JAM'],
    'Epiphone': ['Les Paul Standard', 'SG Standard', 'Casino', 'Dot', 'Hummingbird', 'J-200', 'DR-100']
  }),
  drawing_painting: catalog({
    FaberCastell: ['Polychromos', 'Albrecht Durer', 'Pitt Artist Pen', 'Goldfaber', 'Pitt Pastel', 'Creative Studio', 'Castell 9000'],
    Sakura: ['Pigma Micron', 'Koi Water Colors', 'Gelly Roll', 'Cray-Pas', 'Permapaque', 'SumoGrip', 'Identi-Pen'],
    Copic: ['Sketch', 'Ciao', 'Classic', 'Multiliner SP', 'Acrea', 'Various Ink', 'Opaque White'],
    WinsorNewton: ['Cotman', 'Professional Watercolour', 'Winton', 'Artisan', 'Galeria', 'Promarker', 'Fineliner'],
    Staedtler: ['Mars Lumograph', 'Noris', 'Triplus Fineliner', 'Pigment Liner', 'Ergosoft', 'Karat Aquarell', 'Design Journey'],
    Derwent: ['Inktense', 'Coloursoft', 'Procolour', 'Lightfast', 'Graphitint', 'Metallic', 'Academy'],
    Prismacolor: ['Premier Soft Core', 'Premier Verithin', 'Scholar', 'Col-Erase', 'Art Stix', 'Illustration Marker', 'NuPastel'],
    CaranDAche: ['Luminance 6901', 'Pablo', 'Supracolor', 'Museum Aquarelle', 'Neocolor II', 'Pastel Pencils', 'Grafwood'],
    Pentel: ['Brush Sign Pen', 'Pocket Brush', 'GraphGear 1000', 'EnerGel', 'Oil Pastels', 'Aqua Brush', 'Color Brush'],
    Arteza: ['EverBlend', 'Real Brush Pens', 'Expert Watercolor', 'Acrylic Paint', 'Colored Pencils', 'Sketchbook', 'Gouache']
  }),
  handmade_crafts: catalog({
    Cricut: ['Maker 3', 'Explore 3', 'Joy', 'Joy Xtra', 'EasyPress 3', 'Mug Press', 'Autopress'],
    Singer: ['Heavy Duty 4423', 'Heavy Duty 4432', 'Simple 3232', 'M1000', 'Quantum Stylist 9960', 'Tradition 2250', 'Start 1304'],
    Brother: ['CS7000X', 'XM2701', 'SE600', 'SE700', 'PE800', 'Innov-is A80', 'ScanNCut SDX125'],
    DMC: ['Mouline Spécial', 'Color Variations', 'Pearl Cotton', 'Eco Vita', 'Satin', 'Light Effects', 'Diamant'],
    Prym: ['Love', 'Ergonomics', 'Color Snaps', 'Vario', 'Knit Pro', 'Aqua', 'Professional'],
    Clover: ['Amour', 'Soft Touch', 'Wonder Clips', 'Quick Yo-Yo', 'Pom-Pom Maker', 'Takumi', 'Chaco Liner'],
    Fiskars: ['Amplify', 'Easy Action', 'Classic Scissors', 'Rotary Cutter', 'SureCut', 'Precision Knife', 'Paper Trimmer'],
    OLFA: ['RTY-2', 'RTY-3', 'L-1', 'AK-1', 'CMP-1', 'PRC-3', 'FQR-4'],
    Janome: ['HD3000', '2212', 'Sewist 725S', 'Memory Craft 6700P', 'Skyline S5', 'AirThread 2000D', 'CoverPro 2000CPX'],
    Bernina: ['B 335', 'B 435', 'B 570 QE', 'B 770 QE', 'B 790 PLUS', 'L 850', 'Q 16']
  }),
  board_games_puzzles: catalog({
    Hasbro: ['Monopoly', 'Cluedo', 'Risk', 'Scrabble', 'Operation', 'Jenga', 'Twister'],
    Ravensburger: ['Labyrinth', 'Villainous', 'Disney Lorcana', 'GraviTrax', 'Scotland Yard', 'The Castles of Burgundy', 'Puzzle 1000'],
    Mattel: ['UNO', 'UNO Flip', 'Skip-Bo', 'Phase 10', 'Blokus', 'Pictionary', 'Apples to Apples'],
    Asmodee: ['Dobble', 'Ticket to Ride', '7 Wonders', 'Catan', 'Dixit', 'Azul', 'Splendor'],
    KOSMOS: ['The Crew', 'EXIT', 'Catan', 'Ubongo', 'Lost Cities', 'Adventure Games', 'Imhotep'],
    Stonemaier: ['Wingspan', 'Scythe', 'Viticulture', 'Tapestry', 'Between Two Cities', 'Apiary', 'Red Rising'],
    DaysOfWonder: ['Ticket to Ride', 'Small World', 'Heat', 'Memoir 44', 'Five Tribes', 'Deep Blue', 'Shadows over Camelot'],
    ExplodingKittens: ['Exploding Kittens', 'Throw Throw Burrito', 'Poetry for Neanderthals', 'Happy Salmon', 'Barking Kittens', 'Zombie Kittens', 'A Game of Cat & Mouth'],
    HABA: ['Animal Upon Animal', 'First Orchard', 'Rhino Hero', 'Monza', 'Karuba', 'The Magic Labyrinth', 'My Very First Games'],
    BlueOrange: ['Spot It!', 'Kingdomino', 'Photosynthesis', 'Planet', 'Dr Eureka', 'Gobblet', 'Next Station London']
  }),
  camping_travel: catalog({
    Coleman: ['Sundome', 'Skydome', 'Instant Cabin', 'RoadTrip', 'Cascade', 'Brazos', 'Triton'],
    MSR: ['Hubba Hubba', 'Elixir 2', 'PocketRocket 2', 'WhisperLite', 'WindBurner', 'Guardian', 'Reactor'],
    BigAgnes: ['Copper Spur HV UL2', 'Tiger Wall UL2', 'Fly Creek HV UL2', 'Rapide SL', 'Lost Ranger', 'Blacktail', 'Skyline UL'],
    Naturehike: ['Cloud Up 2', 'Mongar 2', 'Star River 2', 'Rock 60+5', 'CWM400', 'Yunue', 'Vik 1'],
    Nemo: ['Dagger OSMO', 'Hornet OSMO', 'Dragonfly OSMO', 'Tensor', 'Quasar 3D', 'Disco', 'Fillo'],
    SeaToSummit: ['Ether Light XT', 'Spark', 'Trek', 'Telos TR2', 'Alto TR2', 'Aeros', 'X-Pot'],
    SnowPeak: ['Amenity Dome', 'Land Lock', 'Takibi Fire & Grill', 'Titanium Mug', 'Home & Camp Burner', 'Alpha Breeze', 'Entry Pack TT'],
    Quechua: ['2 Seconds', 'MH100', 'MH500', 'Fresh & Black', 'Arpenaz', 'Comfort 65', 'Inflatable Air Seconds'],
    'The North Face': ['Wawona 6', 'Stormbreak 2', 'Homestead', 'Base Camp Duffel', 'One Bag', 'Eco Trail Bed', 'Trail Lite'],
    Osprey: ['Farpoint 40', 'Fairview 40', 'Atmos AG 65', 'Aether 65', 'Talon 22', 'Daylite', 'Transporter']
  }),
  gardening_plants: catalog({
    Fiskars: ['PowerGear X', 'Solid', 'Xact', 'QuikFit', 'SmartFit', 'StaySharp', 'Garden Pro'],
    Gardena: ['Classic', 'Comfort', 'Premium', 'Micro-Drip', 'AquaZoom', 'Sileno', 'Smart System'],
    Bosch: ['EasyPrune', 'UniversalHedgeCut', 'Rotak', 'AdvancedGrassCut', 'EasyGrassCut', 'AHS 50-20', 'UniversalAquatak'],
    Makita: ['DUR181', 'DUR368', 'DUH523', 'DLM432', 'DLM462', 'DUC353', 'DUB184'],
    Husqvarna: ['Automower 305', 'Automower 450X', '120 Mark II', '129R', '525RX', 'LC 247S', '122HD60'],
    STIHL: ['MS 170', 'MS 250', 'FSA 57', 'FS 55', 'HSA 45', 'RMA 339', 'BGA 57'],
    Karcher: ['K 2', 'K 3', 'K 4', 'K 5', 'K 7', 'BP 3', 'S 4 Twin'],
    Ryobi: ['ONE+ Trimmer', 'ONE+ Hedge Trimmer', 'ONE+ Blower', 'ONE+ Mower', 'ONE+ Pruner', 'ONE+ Cultivator', 'ONE+ Sprayer'],
    BlackDecker: ['BESTA530', 'GL360', 'GKC1825L20', 'GSL700', 'BCASST91B', 'BEHT201', 'BEMW451'],
    Einhell: ['GE-CM 36', 'GE-CT 18', 'GE-HC 18', 'GE-LC 18', 'GE-CH 1855', 'GC-PM 46', 'AQUINNA']
  }),
  cooking: catalog({
    LeCreuset: ['Signature', 'Classic', 'Toughened Nonstick', 'Stoneware', '3-Ply', 'Kone', 'TNS Pro'],
    Lodge: ['L8SK3', 'L10SK3', 'L12SK3', 'Combo Cooker', 'Double Dutch Oven', 'Chef Collection', 'Blacklock'],
    Tefal: ['Ingenio', 'Unlimited', 'Jamie Oliver', 'Daily Cook', 'Cook & Clean', 'Duetto', 'Easy Cook'],
    Zwilling: ['Pro', 'Four Star', 'Twin Gourmet', 'Simplify', 'Vitality', 'Enfinigy', 'Fresh & Save'],
    KitchenAid: ['Artisan', 'Classic', 'Professional 600', 'Bowl-Lift', 'Cordless', 'Food Processor', 'K400'],
    Breville: ['Barista Express', 'Smart Oven Air', 'Fast Slow Pro', 'Super Q', 'Juice Fountain', 'Custom Loaf', 'Control Grip'],
    Ninja: ['Foodi', 'Dual Zone', 'Creami', 'Speedi', 'Woodfire', 'Combi', 'Blast'],
    Philips: ['Airfryer XL', 'Airfryer XXL', 'All-in-One Cooker', 'Daily Collection', 'Viva Collection', 'Avance Collection', '5000 Series'],
    InstantPot: ['Duo', 'Duo Plus', 'Pro', 'Pro Plus', 'Rio', 'Vortex', 'Omni'],
    Thermomix: ['TM7', 'TM6', 'TM5', 'TM31', 'Friend', 'Sensor', 'Cookidoo']
  }),
  collecting: catalog({
    LEGO: ['Star Wars', 'Technic', 'Icons', 'Architecture', 'Ideas', 'Minifigures', 'Speed Champions'],
    Funko: ['Pop! Vinyl', 'Pop! Rides', 'Pop! Deluxe', 'Pop! Moments', 'Soda', 'Mystery Minis', 'Bitty Pop!'],
    HotWheels: ['Mainline', 'Premium Car Culture', 'Team Transport', 'RLC', 'Elite 64', 'Monster Trucks', 'Track Builder'],
    Pokemon: ['Scarlet & Violet', 'Prismatic Evolutions', 'Surging Sparks', '151', 'Paldean Fates', 'Temporal Forces', 'Twilight Masquerade'],
    Bandai: ['HG Gundam', 'RG Gundam', 'MG Gundam', 'PG Gundam', 'S.H.Figuarts', 'Figure-rise', 'Tamashii Nations'],
    Hasbro: ['Marvel Legends', 'Star Wars Black Series', 'Transformers Studio Series', 'G.I. Joe Classified', 'Nerf', 'Monopoly', 'My Little Pony'],
    Mattel: ['Barbie Signature', 'Hot Wheels Premium', 'Masters of the Universe', 'Monster High', 'WWE Elite', 'Matchbox', 'Polly Pocket'],
    PopMart: ['Labubu', 'Molly', 'Skullpanda', 'Dimoo', 'Hirono', 'Crybaby', 'Pucky'],
    GoodSmile: ['Nendoroid', 'figma', 'POP UP PARADE', 'MODEROID', 'Nendoroid Doll', 'Harmonia', 'HELLO! GOOD SMILE'],
    Panini: ['FIFA World Cup', 'Premier League', 'Adrenalyn XL', 'Prizm', 'Select', 'Donruss', 'Chronicles']
  })
} as const;
