type BrandWithLogo = { name: string; logoSlug?: string; logoUrl?: string };

const SIMPLE_ICON_ALIASES: Record<string, string> = {
  'H&M Home': 'handm',
  'H&M Kids': 'handm',
  HM: 'handm',
  'Zara Home': 'zara',
  'Zara Kids': 'zara',
  'Uniqlo Kids': 'uniqlo',
  'Nike Swim': 'nike',
  'Nike Kids': 'nike',
  'Adidas Combat': 'adidas',
  'Adidas Kids': 'adidas',
  'Levi Strauss': 'levis',
  'Black+Decker': 'blackanddecker',
  BlackDecker: 'blackanddecker',
  'The North Face': 'thenorthface',
  "L'Oreal": 'loreal',
  "Carter's": 'carters',
  'La Roche-Posay': 'larocheposay',
  'FaberCastell': 'fabercastell',
  'MichaelKors': 'michaelkors',
  'KateSpade': 'katespade',
  'DanielWellington': 'danielwellington',
  PopMart: 'popmart',
  GoodSmile: 'goodsmilecompany'
};

const BRAND_DOMAINS: Record<string, string> = {
  Informa: 'informa.co.id',
  Nitori: 'nitori-net.jp',
  'Herman Miller': 'hermanmiller.com',
  Steelcase: 'steelcase.com',
  'Ashley Furniture': 'ashleyfurniture.com',
  'La-Z-Boy': 'la-z-boy.com',
  Cellini: 'cellini.com.sg',
  Olympic: 'olympicfurniture.co.id',
  'Le Creuset': 'lecreuset.com',
  Tefal: 'tefal.com',
  Zwilling: 'zwilling.com',
  Oxo: 'oxo.com',
  LocknLock: 'locknlock.com',
  Pyrex: 'pyrexhome.com',
  Luminarc: 'luminarc.com',
  'Joseph Joseph': 'josephjoseph.com',
  Bormioli: 'bormiolirocco.com',
  Umbra: 'umbra.com',
  'Bloomingville': 'bloomingville.com',
  KaveHome: 'kavehome.com',
  'West Elm': 'westelm.com',
  'Pottery Barn': 'potterybarn.com',
  'Pottery Barn Kids': 'potterybarnkids.com',
  Krisbow: 'krisbow.com',
  'King Koil': 'kingkoil.com',
  Tencel: 'tencel.com',
  Kintakun: 'kintakun.co.id',
  Serta: 'serta.com',
  Makita: 'makita.com',
  DeWalt: 'dewalt.com',
  Stanley: 'stanleytools.com',
  Milwaukee: 'milwaukeetool.com',
  Ryobi: 'ryobitools.com',
  INGCO: 'ingco.com',
  'Tommy Hilfiger': 'tommy.com',
  'Ralph Lauren': 'ralphlauren.com',
  Mango: 'shop.mango.com',
  'Massimo Dutti': 'massimodutti.com',
  'Marks & Spencer': 'marksandspencer.com',
  CottonOn: 'cottonon.com',
  Coach: 'coach.com',
  Longchamp: 'longchamp.com',
  MichaelKors: 'michaelkors.com',
  KateSpade: 'katespade.com',
  Kipling: 'kipling.com',
  Herschel: 'herschel.com',
  Fjallraven: 'fjallraven.com',
  'Charles & Keith': 'charleskeith.com',
  Samsonite: 'samsonite.com',
  Maybelline: 'maybelline.com',
  Cetaphil: 'cetaphil.com',
  CeraVe: 'cerave.com',
  'The Ordinary': 'theordinary.com',
  'La Roche-Posay': 'laroche-posay.com',
  Wardah: 'wardahbeauty.com',
  Somethinc: 'somethinc.com',
  Emina: 'eminacosmetics.com',
  Cybex: 'cybex-online.com',
  Joie: 'joiebaby.com',
  Chicco: 'chicco.com',
  'Maxi-Cosi': 'maxi-cosi.com',
  Bugaboo: 'bugaboo.com',
  Nuna: 'nunababy.com',
  UPPAbaby: 'uppababy.com',
  Graco: 'gracobaby.com',
  Babyzen: 'babyzen.com',
  Doona: 'doona.com',
  "Carter's": 'carters.com',
  OshKosh: 'oshkosh.com',
  Mothercare: 'mothercare.com',
  'Mamas & Papas': 'mamasandpapas.com',
  'Gap Kids': 'gap.com',
  'Fisher-Price': 'fisher-price.com',
  Playmobil: 'playmobil.com',
  VTech: 'vtechkids.com',
  Ravensburger: 'ravensburger.com',
  MelissaDoug: 'melissaanddoug.com',
  Hape: 'hape.com',
  Schleich: 'schleich-s.com',
  Stokke: 'stokke.com',
  Babyletto: 'babyletto.com',
  'Delta Children': 'deltachildren.com',
  'Dream On Me': 'dreamonme.com',
  'Tutti Bambini': 'tuttibambini.com',
  Sebra: 'sebra-interior.com',
  'Channel Islands': 'cisurfboards.com',
  Firewire: 'firewiresurfboards.com',
  Lost: 'lostsurfboards.net',
  JS: 'us.jsindustries.com',
  Pyzel: 'pyzelsurfboards.com',
  DHD: 'dhdsurf.com',
  Haydenshapes: 'haydenshapes.com',
  'Sharp Eye': 'sharpeyesurfboards.com',
  Torq: 'torq-surfboards.com',
  Softech: 'softechsoftboards.com',
  Bowflex: 'bowflex.com',
  Technogym: 'technogym.com',
  NordicTrack: 'nordictrack.com',
  'Life Fitness': 'lifefitness.com',
  'Rogue Fitness': 'roguefitness.com',
  Peloton: 'onepeloton.com',
  Concept2: 'concept2.com',
  TRX: 'trxtraining.com',
  Manduka: 'manduka.com',
  Liforme: 'liforme.com',
  JadeYoga: 'jadeyoga.com',
  AloYoga: 'aloyoga.com',
  Gaiam: 'gaiam.com',
  'B Yoga': 'byoganow.com',
  YogiBare: 'yogibare.com',
  'Hugger Mugger': 'huggermugger.com',
  'Yoga Design Lab': 'yogadesignlab.com',
  Bullpadel: 'bullpadel.com',
  Nox: 'noxsport.com',
  Siux: 'siuxpadel.com',
  Head: 'head.com',
  StarVie: 'starvie.com',
  Varlion: 'varlion.com',
  'Black Crown': 'blackcrown.es',
  Babolat: 'babolat.com',
  Wilson: 'wilson.com',
  Yonex: 'yonex.com',
  Dunlop: 'dunlopsports.com',
  Prince: 'princetennis.com',
  Tecnifibre: 'tecnifibre.com',
  Solinco: 'solincosports.com',
  Speedo: 'speedo.com',
  Arena: 'arenasport.com',
  TYR: 'tyr.com',
  FINIS: 'finis.co',
  Zoggs: 'zoggs.com',
  AquaSphere: 'aquasphereswim.com',
  MadWave: 'madwave.com',
  Funkita: 'funkita.com',
  Venum: 'venum.com',
  Fairtex: 'fairtex.com',
  'Twins Special': 'twinsfightgear.com',
  Hayabusa: 'hayabusafight.com',
  Everlast: 'everlast.com',
  'Cleto Reyes': 'cletoreyesboxing.com',
  RDX: 'rdxsports.com',
  Cressi: 'cressi.com',
  Mares: 'mares.com',
  Scubapro: 'scubapro.com',
  Aqualung: 'aqualung.com',
  Oceanic: 'oceanicworldwide.com',
  Apeks: 'apeksdiving.com',
  TUSA: 'tusa.com',
  Hollis: 'hollis.com',
  SEAC: 'seacsub.com',
  'Ocean Reef': 'oceanreefgroup.com',
  Apacs: 'apacssports.com',
  'Santa Cruz': 'santacruzskateboards.com',
  Element: 'elementbrand.com',
  Girl: 'girlskateboards.com',
  Chocolate: 'chocolateskateboards.com',
  'Powell Peralta': 'powell-peralta.com',
  AntiHero: 'antiheroskateboards.com',
  Baker: 'bakerskateboards.com',
  Arbor: 'arborcollective.com',
  'Sector 9': 'sector9.com',
  Landyachtz: 'landyachtz.com',
  Mikasa: 'mikasasports.co.jp',
  Molten: 'molten.co.jp',
  HOKA: 'hoka.com',
  Brooks: 'brooksrunning.com',
  Saucony: 'saucony.com',
  On: 'on.com',
  Osprey: 'osprey.com',
  Deuter: 'deuter.com',
  'Black Diamond': 'blackdiamondequipment.com',
  Leki: 'leki.com',
  Titleist: 'titleist.com',
  Callaway: 'callawaygolf.com',
  TaylorMade: 'taylormadegolf.com',
  Srixon: 'srixon.com',
  Honma: 'honmagolf.com',
  Cricut: 'cricut.com',
  DMC: 'dmc.com',
  Prym: 'prym.com',
  Clover: 'clover-usa.com',
  OLFA: 'olfa.com',
  Bernina: 'bernina.com',
  Asmodee: 'asmodee.com',
  KOSMOS: 'kosmos.de',
  Stonemaier: 'stonemaiergames.com',
  DaysOfWonder: 'daysofwonder.com',
  ExplodingKittens: 'explodingkittens.com',
  HABA: 'haba-play.com',
  Coleman: 'coleman.com',
  MSR: 'msrgear.com',
  BigAgnes: 'bigagnes.com',
  Naturehike: 'naturehike.com',
  Nemo: 'nemoequipment.com',
  SeaToSummit: 'seatosummit.com',
  SnowPeak: 'snowpeak.com',
  Gardena: 'gardena.com',
  Husqvarna: 'husqvarna.com',
  STIHL: 'stihl.com',
  Einhell: 'einhell.com',
  Lodge: 'lodgecastiron.com',
  Thermomix: 'thermomix.com',
  Funko: 'funko.com',
  PopMart: 'popmart.com',
  GoodSmile: 'goodsmile.com'
};

const asciiName = (name: string) => name.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase();

const localLogoSlug = (name: string) => asciiName(name)
  .replace(/&/g, 'and')
  .replace(/\+/g, 'plus')
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/^-|-$/g, '');

export const getMarketBrandLogoSources = (brand: BrandWithLogo): string[] => {
  const normalized = asciiName(brand.name);
  const explicitSlug = brand.logoSlug ?? SIMPLE_ICON_ALIASES[brand.name];
  const simpleSlug = explicitSlug
    ?? normalized.replace(/&/g, 'and').replace(/\+/g, 'plus').replace(/[^a-z0-9]/g, '');
  const iconifySlug = normalized.replace(/&/g, 'and').replace(/\+/g, 'plus').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  const domain = BRAND_DOMAINS[brand.name];
  const sources = [
    `/brand-logos/${localLogoSlug(brand.name)}.svg`,
    brand.logoUrl,
    explicitSlug ? `https://cdn.simpleicons.org/${explicitSlug}/1E293B` : undefined,
    domain ? `https://${domain}/favicon.ico` : undefined,
    !domain && !explicitSlug ? `https://cdn.simpleicons.org/${simpleSlug}/1E293B` : undefined,
    !domain ? `https://api.iconify.design/logos/${iconifySlug}.svg` : undefined
  ];
  return [...new Set(sources.filter((source): source is string => Boolean(source)))];
};
