type ServiceOption = { id: string; en: string; ru: string };

export const SERVICE_SUBCATEGORIES: Record<string, ServiceOption[]> = {
  household_services: [
    { id: 'household_services.cleaning', en: "Cleaning", ru: "Уборка" },
    { id: 'household_services.laundry_and_dry_cleaning', en: "Laundry and dry cleaning", ru: "Стирка и химчистка" },
    { id: 'household_services.appliance_repair', en: "Appliance repair", ru: "Ремонт техники" },
    { id: 'household_services.electrical_work', en: "Electrical work", ru: "Электрика" },
    { id: 'household_services.plumbing', en: "Plumbing", ru: "Сантехника" },
    { id: 'household_services.air_conditioning', en: "Air conditioning", ru: "Кондиционеры" },
    { id: 'household_services.renovation_and_construction', en: "Renovation and construction", ru: "Ремонт и строительство" },
    { id: 'household_services.furniture_assembly', en: "Furniture assembly", ru: "Сборка мебели" },
    { id: 'household_services.garden_and_pool', en: "Garden and pool", ru: "Сад и бассейн" },
    { id: 'household_services.pest_control', en: "Pest control", ru: "Борьба с насекомыми" },
    { id: 'household_services.moving_and_delivery', en: "Moving and delivery", ru: "Переезд и доставка" },
    { id: 'household_services.other', en: "Other", ru: "Другое" },
  ],
  beauty_care: [
    { id: 'beauty_care.hairdresser', en: "Hairdresser", ru: "Парикмахер" },
    { id: 'beauty_care.barber', en: "Barber", ru: "Барбер" },
    { id: 'beauty_care.manicure_and_pedicure', en: "Manicure and pedicure", ru: "Маникюр и педикюр" },
    { id: 'beauty_care.brows_and_lashes', en: "Brows and lashes", ru: "Брови и ресницы" },
    { id: 'beauty_care.makeup', en: "Makeup", ru: "Макияж" },
    { id: 'beauty_care.cosmetology', en: "Cosmetology", ru: "Косметология" },
    { id: 'beauty_care.massage_and_spa', en: "Massage and SPA", ru: "Массаж и SPA" },
    { id: 'beauty_care.hair_removal', en: "Hair removal", ru: "Эпиляция" },
    { id: 'beauty_care.tattoo_and_piercing', en: "Tattoo and piercing", ru: "Тату и пирсинг" },
    { id: 'beauty_care.body_care', en: "Body care", ru: "Уход за телом" },
    { id: 'beauty_care.stylist', en: "Stylist", ru: "Стилист" },
    { id: 'beauty_care.other', en: "Other", ru: "Другое" },
  ],
  health: [
    { id: 'health.medical_consultations', en: "Medical consultations", ru: "Врачебные консультации" },
    { id: 'health.dentistry', en: "Dentistry", ru: "Стоматология" },
    { id: 'health.psychologist', en: "Psychologist", ru: "Психолог" },
    { id: 'health.physiotherapy_and_rehabilitation', en: "Physiotherapy and rehabilitation", ru: "Физиотерапия и реабилитация" },
    { id: 'health.therapeutic_massage', en: "Therapeutic massage", ru: "Лечебный массаж" },
    { id: 'health.osteopathy_and_manual_therapy', en: "Osteopathy and manual therapy", ru: "Остеопатия и мануальная терапия" },
    { id: 'health.dietitian_and_nutritionist', en: "Dietitian and nutritionist", ru: "Диетолог и нутрициолог" },
    { id: 'health.tests_and_diagnostics', en: "Tests and diagnostics", ru: "Анализы и диагностика" },
    { id: 'health.home_nursing', en: "Home nursing", ru: "Медсестра на дом" },
    { id: 'health.alternative_medicine', en: "Alternative medicine", ru: "Альтернативная медицина" },
    { id: 'health.health_insurance', en: "Health insurance", ru: "Страхование здоровья" },
    { id: 'health.other', en: "Other", ru: "Другое" },
  ],
  education: [
    { id: 'education.foreign_languages', en: "Foreign languages", ru: "Иностранные языки" },
    { id: 'education.tutors', en: "Tutors", ru: "Репетиторы" },
    { id: 'education.children_s_education', en: "Children's education", ru: "Детское обучение" },
    { id: 'education.music_and_singing', en: "Music and singing", ru: "Музыка и вокал" },
    { id: 'education.art_and_creativity', en: "Art and creativity", ru: "Рисование и творчество" },
    { id: 'education.dance', en: "Dance", ru: "Танцы" },
    { id: 'education.cooking_classes', en: "Cooking classes", ru: "Кулинарные занятия" },
    { id: 'education.computers_and_it', en: "Computers and IT", ru: "Компьютеры и IT" },
    { id: 'education.business_and_professions', en: "Business and professions", ru: "Бизнес и профессии" },
    { id: 'education.courses_and_workshops', en: "Courses and workshops", ru: "Курсы и мастер-классы" },
    { id: 'education.exam_preparation', en: "Exam preparation", ru: "Подготовка к экзаменам" },
    { id: 'education.other', en: "Other", ru: "Другое" },
  ],
  sport: [
    { id: 'sport.fitness', en: "Fitness", ru: "Фитнес" },
    { id: 'sport.yoga', en: "Yoga", ru: "Йога" },
    { id: 'sport.surfing', en: "Surfing", ru: "Сёрфинг" },
    { id: 'sport.padel', en: "Padel", ru: "Падел" },
    { id: 'sport.tennis', en: "Tennis", ru: "Теннис" },
    { id: 'sport.swimming', en: "Swimming", ru: "Плавание" },
    { id: 'sport.martial_arts', en: "Martial arts", ru: "Единоборства" },
    { id: 'sport.diving_and_snorkeling', en: "Diving and snorkeling", ru: "Дайвинг и снорклинг" },
    { id: 'sport.dance', en: "Dance", ru: "Танцы" },
    { id: 'sport.pilates_and_stretching', en: "Pilates and stretching", ru: "Пилатес и растяжка" },
    { id: 'sport.team_sports', en: "Team sports", ru: "Командные виды спорта" },
    { id: 'sport.trekking_and_outdoor_activities', en: "Trekking and outdoor activities", ru: "Трекинг и активный отдых" },
    { id: 'sport.other_sports', en: "Other sports", ru: "Другой спорт" },
  ],
  photo_video: [
    { id: 'photo_video.photo_shoot', en: "Photo shoot", ru: "Фотосессия" },
    { id: 'photo_video.wedding_photography', en: "Wedding photography", ru: "Свадебная съёмка" },
    { id: 'photo_video.family_photography', en: "Family photography", ru: "Семейная съёмка" },
    { id: 'photo_video.love_story', en: "Love story", ru: "Love story" },
    { id: 'photo_video.social_media_content', en: "Social media content", ru: "Контент для соцсетей" },
    { id: 'photo_video.product_photography', en: "Product photography", ru: "Предметная съёмка" },
    { id: 'photo_video.real_estate_photography', en: "Real estate photography", ru: "Съёмка недвижимости" },
    { id: 'photo_video.aerial_photography', en: "Aerial photography", ru: "Аэросъёмка" },
    { id: 'photo_video.videography', en: "Videography", ru: "Видеосъёмка" },
    { id: 'photo_video.video_editing', en: "Video editing", ru: "Монтаж видео" },
    { id: 'photo_video.photo_editing', en: "Photo editing", ru: "Обработка фотографий" },
    { id: 'photo_video.full_service_production', en: "Full-service production", ru: "Продакшен полного цикла" },
    { id: 'photo_video.other', en: "Other", ru: "Другое" },
  ],
  consultations: [
    { id: 'consultations.legal', en: "Legal", ru: "Юридические" },
    { id: 'consultations.visas_and_immigration', en: "Visas and immigration", ru: "Визы и иммиграция" },
    { id: 'consultations.taxes_and_accounting', en: "Taxes and accounting", ru: "Налоги и бухгалтерия" },
    { id: 'consultations.real_estate', en: "Real estate", ru: "Недвижимость" },
    { id: 'consultations.financial', en: "Financial", ru: "Финансовые" },
    { id: 'consultations.insurance', en: "Insurance", ru: "Страхование" },
    { id: 'consultations.career_and_resume', en: "Career and resume", ru: "Карьера и резюме" },
    { id: 'consultations.psychology_and_relationships', en: "Psychology and relationships", ru: "Психология и отношения" },
    { id: 'consultations.relocation_and_adaptation', en: "Relocation and adaptation", ru: "Переезд и адаптация" },
    { id: 'consultations.document_translation', en: "Document translation", ru: "Перевод документов" },
    { id: 'consultations.other_consultations', en: "Other consultations", ru: "Другие консультации" },
  ],
  service_business: [
    { id: 'service_business.business_registration', en: "Business registration", ru: "Регистрация бизнеса" },
    { id: 'service_business.accounting', en: "Accounting", ru: "Бухгалтерия" },
    { id: 'service_business.legal_support', en: "Legal support", ru: "Юридическое сопровождение" },
    { id: 'service_business.marketing_and_advertising', en: "Marketing and advertising", ru: "Маркетинг и реклама" },
    { id: 'service_business.smm_and_content', en: "SMM and content", ru: "SMM и контент" },
    { id: 'service_business.websites_and_apps', en: "Websites and apps", ru: "Создание сайтов и приложений" },
    { id: 'service_business.design_and_branding', en: "Design and branding", ru: "Дизайн и брендинг" },
    { id: 'service_business.business_photography_and_video', en: "Business photography and video", ru: "Фото и видео для бизнеса" },
    { id: 'service_business.recruitment', en: "Recruitment", ru: "Подбор персонала" },
    { id: 'service_business.translation_and_localization', en: "Translation and localization", ru: "Перевод и локализация" },
    { id: 'service_business.business_assistants', en: "Business assistants", ru: "Бизнес-ассистенты" },
    { id: 'service_business.workspace_rental', en: "Workspace rental", ru: "Аренда рабочих мест" },
    { id: 'service_business.equipment_and_supplies', en: "Equipment and supplies", ru: "Оборудование и снабжение" },
    { id: 'service_business.other', en: "Other", ru: "Другое" },
  ],
  service_transport: [
    { id: 'service_transport.airport_transfer', en: "Airport transfer", ru: "Трансфер из аэропорта" },
    { id: 'service_transport.taxi_with_driver', en: "Taxi with driver", ru: "Такси с водителем" },
    { id: 'service_transport.rental_with_driver', en: "Rental with driver", ru: "Аренда с водителем" },
    { id: 'service_transport.intercity_travel', en: "Intercity travel", ru: "Междугородние поездки" },
    { id: 'service_transport.tours_with_driver', en: "Tours with driver", ru: "Экскурсии с водителем" },
    { id: 'service_transport.freight_transport', en: "Freight transport", ru: "Грузоперевозки" },
    { id: 'service_transport.delivery', en: "Delivery", ru: "Доставка" },
    { id: 'service_transport.towing', en: "Towing", ru: "Эвакуатор" },
    { id: 'service_transport.motorbike_transport', en: "Motorbike transport", ru: "Перевозка байков" },
    { id: 'service_transport.moving', en: "Moving", ru: "Переезд" },
    { id: 'service_transport.water_transport', en: "Water transport", ru: "Водный транспорт" },
    { id: 'service_transport.vehicle_repair', en: "Vehicle repair", ru: "Ремонт транспорта" },
    { id: 'service_transport.other', en: "Other", ru: "Другое" },
  ],
  other_services: [
    { id: 'other_services.event_planning', en: "Event planning", ru: "Организация мероприятий" },
    { id: 'other_services.pet_care', en: "Pet care", ru: "Уход за животными" },
    { id: 'other_services.nanny_and_family_assistance', en: "Nanny and family assistance", ru: "Няня и помощь семье" },
    { id: 'other_services.interpreter', en: "Interpreter", ru: "Переводчик" },
    { id: 'other_services.personal_assistant', en: "Personal assistant", ru: "Персональный помощник" },
    { id: 'other_services.travel_services', en: "Travel services", ru: "Туристические услуги" },
    { id: 'other_services.equipment_rental', en: "Equipment rental", ru: "Аренда оборудования" },
    { id: 'other_services.funeral_and_religious_services', en: "Funeral and religious services", ru: "Ритуальные и религиозные услуги" },
    { id: 'other_services.other', en: "Other", ru: "Другое" },
  ],
};

export const getServiceTranslations = (locale: string): Record<string, string> => ({
  'services.subcategory': locale === 'ru' ? 'Подкатегория' : 'Subcategory',
  'services.license': locale === 'ru' ? 'Наличие лицензии' : 'License available',
  'services.certificates': locale === 'ru' ? 'Профессиональные сертификаты' : 'Professional certificates',
  ...Object.fromEntries(Object.values(SERVICE_SUBCATEGORIES).flat().map(option => [
    `services.type.${option.id}`, locale === 'ru' ? option.ru : option.en
  ]))
});

